version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4623:4623"
    environment:
      - NODE_ENV=production
    restart: unless-stopped

volumes:
  node_modules:
